version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: alfa-postgres
    environment:
      POSTGRES_DB: alfa_dev
      POSTGRES_USER: alfa_user
      POSTGRES_PASSWORD: alfa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - alfa-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: alfa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - alfa-network

  # Frontend (Next.js)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: alfa-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - alfa-network

  # Backend (Fastify)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: alfa-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://alfa_user:alfa_password@postgres:5432/alfa_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - alfa-network

  # Worker (Background jobs)
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    container_name: alfa-worker
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://alfa_user:alfa_password@postgres:5432/alfa_dev
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
    volumes:
      - ./apps/worker:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - alfa-network

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: alfa-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - alfa-network

  grafana:
    image: grafana/grafana:latest
    container_name: alfa-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - alfa-network

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  alfa-network:
    driver: bridge